var annotated_dup =
[
    [ "krap", "namespacekrap.html", [
      [ "ATextValue", "structkrap_1_1ATextValue.html", "structkrap_1_1ATextValue" ],
      [ "AtRule", "classkrap_1_1AtRule.html", "classkrap_1_1AtRule" ],
      [ "Blog", "classkrap_1_1Blog.html", "classkrap_1_1Blog" ],
      [ "BlogEntry", "classkrap_1_1BlogEntry.html", "classkrap_1_1BlogEntry" ],
      [ "ButtonValue", "structkrap_1_1ButtonValue.html", "structkrap_1_1ButtonValue" ],
      [ "CaptionedImage", "classkrap_1_1CaptionedImage.html", "classkrap_1_1CaptionedImage" ],
      [ "Color", "classkrap_1_1Color.html", "classkrap_1_1Color" ],
      [ "Compound", "classkrap_1_1Compound.html", "classkrap_1_1Compound" ],
      [ "constants", "structkrap_1_1constants.html", "structkrap_1_1constants" ],
      [ "Contacts", "classkrap_1_1Contacts.html", "classkrap_1_1Contacts" ],
      [ "css", "structkrap_1_1css.html", "structkrap_1_1css" ],
      [ "CSSClass", "classkrap_1_1CSSClass.html", "classkrap_1_1CSSClass" ],
      [ "CSSElement", "classkrap_1_1CSSElement.html", "classkrap_1_1CSSElement" ],
      [ "CSSRegistry", "classkrap_1_1CSSRegistry.html", "classkrap_1_1CSSRegistry" ],
      [ "Debug", "classkrap_1_1Debug.html", "classkrap_1_1Debug" ],
      [ "DivColumn", "classkrap_1_1DivColumn.html", "classkrap_1_1DivColumn" ],
      [ "DivRow", "classkrap_1_1DivRow.html", "classkrap_1_1DivRow" ],
      [ "DivValue", "structkrap_1_1DivValue.html", "structkrap_1_1DivValue" ],
      [ "Document", "classkrap_1_1Document.html", "classkrap_1_1Document" ],
      [ "DocumentImpl", "classkrap_1_1DocumentImpl.html", "classkrap_1_1DocumentImpl" ],
      [ "Education", "classkrap_1_1Education.html", "classkrap_1_1Education" ],
      [ "Element", "classkrap_1_1Element.html", "classkrap_1_1Element" ],
      [ "FontFamily", "classkrap_1_1FontFamily.html", "classkrap_1_1FontFamily" ],
      [ "FontSize", "classkrap_1_1FontSize.html", "classkrap_1_1FontSize" ],
      [ "FontStyle", "classkrap_1_1FontStyle.html", "classkrap_1_1FontStyle" ],
      [ "FontWeight", "classkrap_1_1FontWeight.html", "classkrap_1_1FontWeight" ],
      [ "GenericException", "classkrap_1_1GenericException.html", "classkrap_1_1GenericException" ],
      [ "Head", "classkrap_1_1Head.html", "classkrap_1_1Head" ],
      [ "Header", "classkrap_1_1Header.html", "classkrap_1_1Header" ],
      [ "Height", "classkrap_1_1Height.html", "classkrap_1_1Height" ],
      [ "Home", "classkrap_1_1Home.html", "classkrap_1_1Home" ],
      [ "ImageValue", "structkrap_1_1ImageValue.html", "structkrap_1_1ImageValue" ],
      [ "JScript", "classkrap_1_1JScript.html", "classkrap_1_1JScript" ],
      [ "LinkValue", "structkrap_1_1LinkValue.html", "structkrap_1_1LinkValue" ],
      [ "MainMenu", "classkrap_1_1MainMenu.html", "classkrap_1_1MainMenu" ],
      [ "MarkdownBlog", "classkrap_1_1MarkdownBlog.html", "classkrap_1_1MarkdownBlog" ],
      [ "MaxHeight", "classkrap_1_1MaxHeight.html", "classkrap_1_1MaxHeight" ],
      [ "MaxWidth", "classkrap_1_1MaxWidth.html", "classkrap_1_1MaxWidth" ],
      [ "MyOssProjects", "classkrap_1_1MyOssProjects.html", "classkrap_1_1MyOssProjects" ],
      [ "MyPublications", "classkrap_1_1MyPublications.html", "classkrap_1_1MyPublications" ],
      [ "ObjectFloat", "classkrap_1_1ObjectFloat.html", "classkrap_1_1ObjectFloat" ],
      [ "Page", "classkrap_1_1Page.html", "classkrap_1_1Page" ],
      [ "ParagraphTextValue", "structkrap_1_1ParagraphTextValue.html", "structkrap_1_1ParagraphTextValue" ],
      [ "Patents", "classkrap_1_1Patents.html", "classkrap_1_1Patents" ],
      [ "ProfExperience", "classkrap_1_1ProfExperience.html", "classkrap_1_1ProfExperience" ],
      [ "Site", "classkrap_1_1Site.html", "classkrap_1_1Site" ],
      [ "TextDecoration", "classkrap_1_1TextDecoration.html", "classkrap_1_1TextDecoration" ],
      [ "TitleValue", "structkrap_1_1TitleValue.html", "structkrap_1_1TitleValue" ],
      [ "Uri", "classkrap_1_1Uri.html", "classkrap_1_1Uri" ],
      [ "Width", "classkrap_1_1Width.html", "classkrap_1_1Width" ]
    ] ]
];