on:
  push:
    branches:
      - main

jobs:
  make_doxygen:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - uses: actions/checkout@v3
      - run: ls -la /home/runner/work/kraposhin-cg-site/kraposhin-cg-site
      - run: ls -la .
      - uses: mattnotmitt/doxygen-action@1.9.5
        with:
          doxyfile-path: './Doxyfile'
      - shell: bash
        run: |
          mkdir /home/runner/work/t-doxy && cd /home/runner/work/t-doxy
          cp -rf /home/runner/work/kraposhin-cg-site/kraposhin-cg-site/doxygen_doc/* ./
          cd /home/runner/work/kraposhin-cg-site/kraposhin-cg-site
          git checkout gh-pages
          mv /home/runner/work/t-doxy/* ./
          git add -A
          git commit -m "gh-pages auto update"
          git push -u origin

#      - uses: actions/upload-artifact@v3
#        with:
#          name: doxy-artifact
#          path: /home/runner/work/kraposhin-cg-site/kraposhin-cg-site/doxygen_doc # or path/to/artifact
        
#uses: mattnotmitt/doxygen-action@1.9.5
#with:
#  doxyfile-path: 'Doxyfile'
