on:
  push:
    branches:
      - main

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
#uses: mattnotmitt/doxygen-action@1.9.5
#with:
#  doxyfile-path: 'Doxyfile'
